on:
  push:
    branches:
      - publish

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[maven-release-plugin]')"
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          server-id: https://github.com

      - run: cat /home/runner/.m2/settings.xml

      - run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Publish JAR
        run: nix develop -c mvn --batch-mode release:prepare release:perform
#        env:
#          GITHUB_ACTOR: ${{ github.actor }}
#          GITHUB_TOKEN: ${{ github.token }}
