on:
  push:
    branches:
      - publish

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'gha@users.noreply.github.com'
          nix develop -c mvn --batch-mode release:prepare
          nix develop -c mvn --batch-mode release:perform
